---
title: "Lobster Exploration"
author: "Clarissa Boyajian"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

### Getting started
```{r}
lobsters <- read_csv(here("data", "Lobster_Abundance_All_Years_20210412.csv"), na = c("-9999", "")) %>% 
  clean_names() %>% 
  uncount(count)
  #this took out the column "count" and instead created one row for each observation    condensed into the "count" column
```

### Task 1: Find counts and mean sizes by site and year
```{r}
lobsters_summary <- lobsters %>% 
  group_by(site, year) %>% 
  summarize(mean_size = (mean(size_mm)),
            total_counts = n())

ggplot(data = lobsters_summary, aes(x = year,
                                    y = total_counts)) +
  geom_line(aes(color = site)) +
  labs(x = "Year",
       y = "Total Count")
```

### Task 2: Find the proportion of legal lobsters at each site for 2020
```{r}
legal_lobsters <- lobsters %>% 
  filter(year == 2020) %>% 
  mutate(legal = case_when(
    size_mm < 79.76 ~ "no",
    size_mm >= 79.76 ~ "yes"
  )) %>% 
  group_by(site, legal) %>% 
  summarize(total_legal = n())

ggplot(data = legal_lobsters, aes(x = site,
                                  y = total_legal,
                                  fill = legal)) +
  geom_col(position = "fill")
  labs(x = "Site Code",
       y = "Total Lobster Count Percent")
```

### Task 3: Random lobster wrangling
`filter()` practice:
```{r}
ex_a <- lobsters %>% 
  filter(site %in% c("IVEE", "CARP", "NAPL"))

ex_b <- lobsters %>% 
  filter(month == 8)

ex_c <- lobsters %>% 
  filter(site == "AQUE" | size_mm > 70)

ex_d <- lobsters %>% 
  filter(site != "NAPL")
```

`group_by() %>% summarize()` practice:
```{r}
ex_e <- lobsters %>% 
  group_by(site) %>% 
  summarize(mean_size = mean(size_mm, na.rm = TRUE),
            sd_size = sd(size_mm, na.rm = TRUE))

ex_f <- lobsters %>% 
  group_by(site, month) %>% 
  summarize(max_size = max(size_mm, na.rm = TRUE))
```

`mutate()` practice:
```{r}
ex_g <- lobsters %>% 
  mutate(size_cm = size_mm * 10)

ex_h <- lobsters %>% 
  mutate(site = tolower(site))

ex_i <- lobsters %>% 
  mutate(area = as.character(area))
```

`case_when()` practice:
```{r}
ex_j <- lobsters %>% 
  mutate(size_bin = case_when(
    size_mm <= 70 ~ "small",
    size_mm >70 ~ "large"
  ))

ex_k <- lobsters %>% 
  mutate(designation = case_when(
    site == "IVEE" | site == "NAPL" ~ "MPA",
    TRUE ~ "not MPA"
  ))
```




